
name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: motisproject/cpp-build:latest

    strategy:
      matrix:
        cxx: [gcc-9, clang-9, clang-9-san]
        mode: [Debug, Release]
        exclude:
        - cxx: clang-9-san
          mode: Release

    steps:
    - uses: actions/checkout@v2

    - name: Download pkg
      run: |
        wget https://git.motis-project.de/dl/pkg/-/jobs/artifacts/master/raw/build/pkg?job=linux-release
        mv pkg\?job=linux-release pkg
        chmod +x pkg

    - name: Download dependencies
      run: ./pkg -l -h

    - name: CMake
      run: cmake-ccache-${{ matrix.cxx }} -G "Ninja" -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.mode }}

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ./utl-test
