name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - name: MSVC Debug
            mode: Debug
          - name: MSVC Release
            mode: Release
          - name: Clang Debug
            mode: Debug
            cmake-opt: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl
            cc: clang-cl
          - name: Clang Release
            mode: Release
            cmake-opt: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl

    steps:
    - uses: actions/checkout@v4

    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install doxygen 🔧
      uses: ssciwr/doxygen-install@v1
      with:
        version: "1.13.2"

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Build
      run: |
        cmake -GNinja -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.config.mode }} ${{ matrix.config.cmake-opt }}
        cmake --build build --target utl-test

    - name: Run tests
      run: build\utl-test.exe
