name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CXX: cl.exe

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup developer console
      run: |
        set WD=%cd%
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
        cd %WD%

    - name: CMake
      run: cmake -GNinja -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: build\utl-test.exe
